### ISSUE TITLE
Harry Potter and the Goblet Of Fire

### ISSUE THREAD

**Issue by Ghary** [spikegrobstein/plex-issues#2]
Mislabeled Movie

**Comment by Ghary** [comment]
Mislab

**Comment by spikegrobstein** [comment]
do you know what movie this is?

**Comment by Ghary** [comment]
Some Kate Beckingsale movie, I can't remember the name of it. I'll find out later

**Comment by spikegrobstein** [comment]
deleted movie and re-downloading in couch potato. re-open if it's still an issue.
