### ISSUE TITLE
Atomic Blonde be boken

### ISSUE THREAD

**Issue by hobbas** [spikegrobstein/plex-issues#8]
Please adhere to the following flow:

1. title the issue with the name of the content
2. tag with the type of media (`tv` or `movie`)
3. tag with the type of issue (eg: `mislabeled`)
4. add a brief description of the issue in the body

(you may not have access to add labels, in that case, just describe the issue in the body of the issue)

**Comment by spikegrobstein** [comment]
mostly fixed. korean subtitles now, but it's the right movie. it's also only 720p, so hopefully a better one will come out and replace it soon.
